# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-09 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('attend_status', models.IntegerField()),
                ('localhost', models.CharField(max_length=100, verbose_name='地点')),
                ('category', models.IntegerField(validators=['上', '榜', '分', '类'])),
                ('task_date', models.DateTimeField(verbose_name='任务时间')),
            ],
            options={
                'db_table': '816_attend',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('group', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': '816_user',
            },
        ),
    ]
